#!/bin/bash

esascaldb=/Users/gogrean/astrosoft/xmmsas_20141104_1833/caldb/esas

proton_scale caldb=$esascaldb mode=1 detector=1 \
    maskfile='mos1S001-sp-fil.fits' specfile='mos1S001-obj-fil.pi'
proton_scale caldb=$esascaldb mode=1 detector=2 \
    maskfile='mos2S002-sp-fil.fits' specfile='mos2S002-obj-fil.pi'
proton_scale caldb=$esascaldb mode=1 detector=3 \
    maskfile='pnS003-sp-fil.fits' specfile='pnS003-obj-fil.pi'



